
const MODEL_PATH = 'modelo/model.json';
let aiModel = null;
let modelLoaded = false;
let usingSimulation = false;

const CLASSES = {
    0: 'Ascaris',
    1: 'Giardia', 
    2: 'Hookworm',
    3: 'Trichuris',
    4: 'Negative'
};

async function initApp() {
    console.log("🧪 Iniciando Detector - DIAGNÓSTICO EXTENDIDO");
    await loadAIModel();
    setupEventListeners();
}

async function loadAIModel() {
    console.log("🔄 CARGANDO MODELO - DIAGNÓSTICO EXTENDIDO");
    updateUIStatus('loading', '0%');
    
    try {
        // 1. Verificar TensorFlow.js
        if (typeof tf === 'undefined') {
            throw new Error('TensorFlow.js no está cargado');
        }
        console.log("✅ TensorFlow.js cargado, versión:", tf.version.tfjs);
        
        // 2. Verificar acceso al modelo
        console.log("🔍 Verificando modelo en:", MODEL_PATH);
        const response = await fetch(MODEL_PATH);
        if (!response.ok) {
            throw new Error(`HTTP ${response.status} - No se puede acceder al modelo`);
        }
        
        // 3. Analizar la estructura del model.json
        const modelData = await response.json();
        console.log("📋 ANALIZANDO ESTRUCTURA DEL MODELO:");
        console.log("- Format:", modelData.format);
        console.log("- Generated by:", modelData.generatedBy);
        
        if (modelData.modelTopology) {
            const topology = modelData.modelTopology;
            console.log("- Tiene modelTopology: ✅");
            
            // Buscar la primera capa
            let firstLayer = null;
            if (topology.model_config && topology.model_config.layers) {
                firstLayer = topology.model_config.layers[0];
                console.log("- Estructura: modelTopology → model_config → layers");
            } else if (topology.config && topology.config.layers) {
                firstLayer = topology.config.layers[0];
                console.log("- Estructura: modelTopology → config → layers");
            }
            
            if (firstLayer) {
                console.log("- Primera capa:", firstLayer.class_name, "-", firstLayer.name);
                if (firstLayer.config) {
                    console.log("- batch_input_shape:", firstLayer.config.batch_input_shape);
                    console.log("- dtype:", firstLayer.config.dtype);
                } else {
                    console.log("❌ Primera capa NO tiene config");
                }
            } else {
                console.log("❌ No se pudo encontrar la primera capa");
            }
        } else {
            console.log("❌ NO tiene modelTopology");
        }
        
        // 4. Cargar el modelo
        console.log("📥 Cargando modelo con tf.loadLayersModel...");
        aiModel = await tf.loadLayersModel(MODEL_PATH, {
            onProgress: (fraction) => {
                const percent = Math.round(fraction * 100);
                updateUIStatus('loading', percent + '%');
            }
        });
        
        console.log("🎉 ¡MODELO CARGADO EXITOSAMENTE!");
        console.log("📐 Inputs:", aiModel.inputs);
        console.log("📤 Outputs:", aiModel.outputs);
        
        if (aiModel.inputs && aiModel.inputs[0]) {
            console.log("✅ Input shape:", aiModel.inputs[0].shape);
        }
        
        // 5. Precalentar
        await warmUpModel();
        
        modelLoaded = true;
        usingSimulation = false;
        console.log("🚀 IA REAL ACTIVADA - MODO SIMULACIÓN DESACTIVADO");
        updateUIStatus('ready');
        
    } catch (error) {
        console.error('💥 ERROR CRÍTICO:', error);
        console.error('💥 Mensaje completo:', error.message);
        await enableSimulationMode();
    }
}

async function warmUpModel() {
    try {
        console.log("🔥 Precalentando modelo...");
        const warmUpTensor = tf.zeros([1, 224, 224, 3]);
        const prediction = await aiModel.predict(warmUpTensor);
        console.log("✅ Precalentamiento exitoso");
        warmUpTensor.dispose();
        prediction.dispose();
    } catch (error) {
        console.warn("⚠️ Error en precalentamiento:", error);
    }
}

async function enableSimulationMode() {
    console.warn("🎭 ACTIVANDO MODO SIMULACIÓN");
    modelLoaded = false;
    usingSimulation = true;
    updateUIStatus('simulation');
}

async function processImage(imageFile) {
    if (!modelLoaded && !usingSimulation) return;
    
    updateUIStatus('processing');
    
    try {
        let results;
        if (usingSimulation) {
            results = await simulatePrediction();
        } else {
            results = await predictWithAI(imageFile);
        }
        displayResults(results);
        updateUIStatus('ready');
    } catch (error) {
        console.error('Error procesando imagen:', error);
        updateUIStatus('error');
    }
}

async function predictWithAI(imageFile) {
    const imageTensor = await loadAndProcessImage(imageFile);
    
    try {
        const prediction = aiModel.predict(imageTensor);
        const results = await prediction.data();
        const processedResults = processPredictionResults(results);
        imageTensor.dispose();
        prediction.dispose();
        return processedResults;
    } catch (error) {
        imageTensor.dispose();
        throw error;
    }
}

async function loadAndProcessImage(file) {
    return new Promise((resolve, reject) => {
        const reader = new FileReader();
        reader.onload = async function(e) {
            const img = new Image();
            img.onload = async function() {
                let tensor = tf.browser.fromPixels(img)
                    .resizeNearestNeighbor([224, 224])
                    .toFloat()
                    .expandDims(0)
                    .div(255.0);
                resolve(tensor);
            };
            img.onerror = () => reject(new Error('Error imagen'));
            img.src = e.target.result;
        };
        reader.onerror = () => reject(new Error('Error archivo'));
        reader.readAsDataURL(file);
    });
}

function processPredictionResults(results) {
    const scores = Array.from(results);
    const maxScore = Math.max(...scores);
    const predictedClass = scores.indexOf(maxScore);
    
    return {
        predictedClass: predictedClass,
        className: CLASSES[predictedClass],
        confidence: (maxScore * 100).toFixed(2),
        scores: scores,
        timestamp: new Date().toLocaleString()
    };
}

async function simulatePrediction() {
    await new Promise(resolve => setTimeout(resolve, 1000));
    
    const randomScores = Array(5).fill(0).map(() => Math.random());
    const total = randomScores.reduce((a, b) => a + b, 0);
    const normalizedScores = randomScores.map(score => score / total);
    const maxScore = Math.max(...normalizedScores);
    const predictedClass = normalizedScores.indexOf(maxScore);
    
    return {
        predictedClass: predictedClass,
        className: CLASSES[predictedClass],
        confidence: (maxScore * 100).toFixed(2),
        scores: normalizedScores,
        timestamp: new Date().toLocaleString(),
        simulation: true
    };
}

function displayResults(results) {
    const resultsDiv = document.getElementById('results');
    if (!resultsDiv) return;
    
    let html = '<div class="result-card">';
    html += '<h3>🔍 RESULTADO DEL ANÁLISIS</h3>';
    html += '<div class="prediction">🎯 <strong>Parásito Detectado:</strong> ' + results.className + '</div>';
    html += '<div class="confidence">📈 <strong>Confianza:</strong> ' + results.confidence + '%</div>';
    
    if (results.simulation) {
        html += '<div class="simulation-warning">⚠️ MODO SIMULACIÓN - DATOS DE PRUEBA</div>';
    } else {
        html += '<div class="real-ai-indicator" style="color: green; font-weight: bold;">✅ ANÁLISIS CON IA REAL</div>';
    }
    
    html += '<div class="timestamp">🕐 ' + results.timestamp + '</div>';
    html += '</div>';
    
    resultsDiv.innerHTML = html;
}

function updateUIStatus(status, data = null) {
    const statusElement = document.getElementById('model-status');
    if (!statusElement) return;
    
    const messages = {
        'loading': '🔄 ' + (data || 'Cargando IA...'),
        'ready': '✅ IA REAL ACTIVA - Sistema listo',
        'simulation': '🎭 MODO SIMULACIÓN - IA no disponible',
        'processing': '🔬 Analizando...',
        'error': '❌ Error'
    };
    
    statusElement.textContent = messages[status] || 'Estado';
}

function setupEventListeners() {
    const uploadInput = document.getElementById('image-upload');
    const uploadArea = document.getElementById('upload-area');
    
    if (uploadInput && uploadArea) {
        uploadInput.addEventListener('change', function(e) {
            if (e.target.files.length > 0) {
                processImage(e.target.files[0]);
            }
        });
        
        uploadArea.addEventListener('click', () => uploadInput.click());
    }
}

document.addEventListener('DOMContentLoaded', initApp);
